apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mongodb-egress
  namespace: microservices
spec:
  podSelector:
    matchLabels:
      app: products-service
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0  # Permita conexões para qualquer IP externo
    ports:
    - protocol: TCP
      port: 27017