apiVersion: v1
kind: Secret
metadata:
  name: mongodb-local-credentials
  namespace: products
type: Opaque
stringData:
  username: "mongodb"
  password: "mongodb-secure-password"
  database: "products"
  uri: "mongodb://mongodb:mongodb-secure-password@mongodb-local:27017/products?authSource=admin"