apiVersion: v1
kind: Secret
metadata:
  name: mongodb-local-credentials
  namespace: microservices
type: Opaque
stringData:
  username: "mongodb"
  password: "mongodb-secure-password"  # Substitua por uma senha forte
  database: "products"
  uri: "mongodb://mongodb:mongodb-secure-password@mongodb-local.microservices.svc.cluster.local:27017/products?authSource=admin"