version: "3.8"
services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    depends_on:
      - sonar_postgres
    container_name: central_sonarqube
    networks:
      - sonar-network

  sonar_postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data
    container_name: sonar_postgres
    networks:
      - sonar-network

volumes:
  sonarqube_data:
    name: central_sonarqube_data
  sonar_postgres_data:
    name: central_sonar_postgres_data

networks:
  sonar-network:
    name: sonarqube-central-network