name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para o SonarQube analisar histórico

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instalar dependências de sistema necessárias para compilar bibliotecas C
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev libgmp-dev

      # Configurar Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: false  # Alterado para false para usar o local padrão

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # Instalar dependências com Poetry na raiz do projeto, não dentro do diretório tech
      - name: Install dependencies
        run: |
          # Exibir a configuração atual do Poetry
          poetry config --list
          
          # Instalar dependências diretamente na raiz do projeto
          poetry install --no-interaction
          
          # Adicionar dependências de teste se não estiverem no pyproject.toml
          poetry add pytest-cov behave --group dev || true
          
          # Verificar se as dependências foram instaladas corretamente
          poetry show
          poetry run pip list

      # Executar testes usando poetry run explicitamente
      - name: Run unit tests with coverage
        run: |
          # Verificar a estrutura do diretório
          ls -la
          
          # Executar os testes na raiz
          poetry run pytest tech/tests --cov=tech --cov-report=xml:coverage.xml --cov-report=term

      - name: Run BDD tests with Behave (if available)
        run: |
          if [ -d "tech/tests/tech/bdd/features/" ]; then
            poetry run behave tech/tests/tech/bdd/features/
          else
            echo "BDD tests directory not found, skipping"
          fi

      # SonarQube scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=products_microservice
            -Dsonar.projectName="Products Microservice"
            -Dsonar.sources=tech
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/__pycache__/**,**/tests/**,**/*.html,**/htmlcov/**
            -Dsonar.coverage.exclusions=tests/**/*,**/test_*.py,**/__init__.py

      # Configurar AWS para ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Preparar Docker Buildx para build multi-plataforma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:latest
            131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            POETRY_VERSION=1.7.1
            INSTALL_DEV=false

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name tech-eks-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl get namespace products || kubectl create namespace products
          
          # Use o latest tag no deploy
          kubectl set image deployment/products-service products-service=131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:latest -n products || kubectl apply -f k8s/deployment.yaml
          
          # Verifique se o serviço já existe, senão, aplique-o
          if [ -f k8s/service.yaml ]; then
            kubectl apply -f k8s/service.yaml
          fi
          
          # Verifique o status do rollout
          kubectl rollout status deployment/products-service -n products --timeout=300s