name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  repository_dispatch:
    types: [trigger-deployment]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    if: github.event_name != 'repository_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: List directory structure
        run: ls -la && ls -la tech && find tech -type d | sort

      - name: Install dependencies with Poetry
        working-directory: ./tech
        run: |
          poetry install
          poetry add pytest pytest-cov behave coverage --group dev
          poetry show

      - name: Run unit tests with coverage
        working-directory: ./tech
        run: |
          poetry run pytest tests --cov=tech --cov-report=xml:coverage.xml --cov-report=term

      - name: Run BDD tests with Behave
        working-directory: ./tech
        run: |
          poetry run behave tests/tech/bdd/features

      - name: Move coverage reports to root
        run: |
          if [ -f tech/coverage.xml ]; then
            cp tech/coverage.xml ./coverage.xml
          fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=products_microservice
            -Dsonar.projectName="Products Microservice"
            -Dsonar.sources=tech
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/__pycache__/**,**/tests/**,**/*.html,**/htmlcov/**,**/.scannerwork/**
            -Dsonar.coverage.exclusions=**/tests/**/*,**/test_*.py,**/__init__.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tech
          file: ./tech/Dockerfile
          push: true
          tags: |
            131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:latest
            131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            POETRY_VERSION=1.5.1

  deploy-normal:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'repository_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name tech-eks-cluster --region us-east-1

      - name: Create namespace if needed
        run: |
          if [ -f tech/k8s/products-service/namespace.yaml ]; then
            kubectl apply -f tech/k8s/products-service/namespace.yaml
          else
            kubectl get namespace products || kubectl create namespace products
          fi

      - name: Deploy to Kubernetes
        run: |
          if [ -f tech/k8s/products-service/NetworkPolicy.yaml ]; then
            kubectl apply -f tech/k8s/products-service/NetworkPolicy.yaml
          fi
          
          if [ -f tech/k8s/products-service/job.yaml ]; then
            JOB_NAME=$(grep -o 'name: [a-zA-Z0-9-]*' tech/k8s/products-service/job.yaml | head -1 | awk '{print $2}')
            kubectl delete job $JOB_NAME -n products --ignore-not-found=true
            kubectl apply -f tech/k8s/products-service/job.yaml
          fi
          
          kubectl set image deployment/products-service products-service=131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:latest -n products || kubectl apply -f tech/k8s/products-service/deployment.yaml
          
          if [ -f tech/k8s/products-service/deployment-mongo.yaml ]; then
            kubectl apply -f tech/k8s/products-service/deployment-mongo.yaml
          fi
          
          kubectl apply -f tech/k8s/products-service/service.yaml
          
          if [ -f tech/k8s/products-service/ingress.yaml ]; then
            kubectl apply -f tech/k8s/products-service/ingress.yaml
          fi

      - name: Trigger other microservices
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/kauan1020/payments_microservice/dispatches \
            -d '{"event_type":"trigger-deployment","client_payload":{"repository":"product_microservice"}}'
            
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/kauan1020/users_microservice/dispatches \
            -d '{"event_type":"trigger-deployment","client_payload":{"repository":"product_microservice"}}'
            
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/kauan1020/orders_microservice/dispatches \
            -d '{"event_type":"trigger-deployment","client_payload":{"repository":"product_microservice"}}'

  deploy-triggered:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name tech-eks-cluster --region us-east-1

      - name: Create namespace if needed
        run: |
          if [ -f tech/k8s/products-service/namespace.yaml ]; then
            kubectl apply -f tech/k8s/products-service/namespace.yaml
          else
            kubectl get namespace products || kubectl create namespace products
          fi

      - name: Deploy to Kubernetes
        run: |
          if [ -f tech/k8s/products-service/NetworkPolicy.yaml ]; then
            kubectl apply -f tech/k8s/products-service/NetworkPolicy.yaml
          fi
          
          if [ -f tech/k8s/products-service/job.yaml ]; then
            JOB_NAME=$(grep -o 'name: [a-zA-Z0-9-]*' tech/k8s/products-service/job.yaml | head -1 | awk '{print $2}')
            kubectl delete job $JOB_NAME -n products --ignore-not-found=true
            kubectl apply -f tech/k8s/products-service/job.yaml
          fi
          
          kubectl set image deployment/products-service products-service=131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/products:latest -n products || kubectl apply -f tech/k8s/products-service/deployment.yaml
          
          if [ -f tech/k8s/products-service/deployment-mongo.yaml ]; then
            kubectl apply -f tech/k8s/products-service/deployment-mongo.yaml
          fi
          
          kubectl apply -f tech/k8s/products-service/service.yaml
          
          if [ -f tech/k8s/products-service/ingress.yaml ]; then
            kubectl apply -f tech/k8s/products-service/ingress.yaml
          fi
